version: "3.8"
services:
  node-app:
    build:
      context: ./node-app
    ports:
      - "3000:3000"
    depends_on:
      - ttyd-app
    environment:
      - DOCKER_HOST=tcp://ttyd-app:2375
    networks:
      - lab-network

  ttyd-app:
    build:
      context: ./ttyd-app
    ports:
      - "7681:7681"
      - "2375:2375"
    privileged: true
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
