version: "3.8"
services:
  node-app:
    build:
      context: ./node-app
    ports:
      - "3000:3000"
    depends_on:
      - ttyd-app

  ttyd-app:
    build:
      context: ./ttyd-app
    ports:
      - "7681:7681"
    privileged: true
